name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, closed ]

jobs:
  test:
    name: ${{matrix.renderer}} on ${{matrix.os}}
    strategy:
      matrix:
        renderer: [gi-gtk,electron]
        os: [ubuntu-latest,macos-latest]
        exclude:
          - os: macos-latest
            renderer: gi-gtk
    runs-on: ${{matrix.os}}

    steps:
    - name: Cache git folder
      uses: actions/cache@v4
      with:
        path: .git
        key: git-folder

    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'true'

    - name: Install nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Compile ${{matrix.renderer}} port on ${{matrix.os}}
      run: nix-shell build-scripts/shell.nix --run 'make all NYXT_RENDERER=${{matrix.renderer}}'

    - name: Test ${{matrix.renderer}} port on ${{matrix.os}}
      env:
        NASDF_NON_INTERACTIVE_TESTS: true
      # It runs the tests for system nyxt, not nyxt/${{matrix.renderer}}.
      run: nix-shell build-scripts/shell.nix --run 'make check'
